# Generated by Django 4.2.11 on 2024-06-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_department_company_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='days_employed',
        ),
        migrations.AlterField(
            model_name='employee',
            name='hired_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
