# Generated by Django 4.2.11 on 2024-06-01 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_employee_days_employed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
    ]
